apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: EKSRadtac-Test
  region: us-east-1

vpc:
  id: $VPC_ID
  cidr: "172.31.0.0/16"
  subnets:
    public:
      us-east-1a:
        id: subnet-id
      us-east-1b:
        id: subnet-id

nodeGroups:
  - name: ng-1-workers
    instanceType: t2.medium
    desiredCapacity: 2
